//跨域代理前缀
const BASE_URL = window.SITE_CONFIG.eip.baseURL
module.exports = {
    SystemLogin: `${BASE_URL}/authorize/account/login`,
    SystemLoginByUserId: `${BASE_URL}/authorize/account/login/userid`,
    SystemLoginByCode: `${BASE_URL}/authorize/account/login/code`,
    SystemLogout: `${BASE_URL}/authorize/account/logout`,
    SystemLoginOauth: `${BASE_URL}/authorize/account/login/oauth`,
    SystemLoginOauthCalback: `${BASE_URL}/authorize/account/login/oauth/calback`,
    SystemLoginRefreshToken: `${BASE_URL}/authorize/account/refresh/token`,

    SystemSerialNoCreate: `${BASE_URL}/system/serialno/create`,

    SystemCaptcha: `${BASE_URL}/authorize/account/captcha`,
    SystemUserMenu: `${BASE_URL}/system/home/menu`,
    SystemUserMenuTree: `${BASE_URL}/system/home/menutree`,
    SystemUserMenuAgile: `${BASE_URL}/system/home/menu/agile`,

    SystemMonitorOnlineUser: `${BASE_URL}/system/monitor/onlineuser`,
    SystemMonitorOnlineUserKickout: `${BASE_URL}/system/monitor/onlineuser/kickout`,
    SystemMonitorAssemblies: `${BASE_URL}/system/monitor/assemblies`,
    SystemMonitorApi: `${BASE_URL}/system/monitor/api`,
    SystemMonitorServerBase: `${BASE_URL}/system/monitor/serverbase`,
    SystemMonitorServerDisk: `${BASE_URL}/system/monitor/serverdisk`,
    SystemMonitorServerUsed: `${BASE_URL}/system/monitor/serverused`,

    SystemConfigQuery: `${BASE_URL}/system/config`,
    SystemConfigSave: `${BASE_URL}/system/config`,
    SystemConfigLogin: `${BASE_URL}/system/config/login`,
    SystemConfigSystem: `${BASE_URL}/system/config/system`,

    SystemShortCutQuery: `${BASE_URL}/system/shortcut/user`,
    SystemShortCutSave: `${BASE_URL}/system/shortcut`,
    SystemShortCutDel: `${BASE_URL}/system/shortcut/del`,
    SystemShortCutDelAll: `${BASE_URL}/system/shortcut/delall`,
    SystemShortCutSaveOrderNo: `${BASE_URL}/system/shortcut/order`,

    SystemMenu: `${BASE_URL}/system/menu`,
    SystemMenuApp: `${BASE_URL}/system/menu/app`,
    SystemMenuQuery: `${BASE_URL}/system/menu/list`,
    SystemMenuSave: `${BASE_URL}/system/menu`,
    SystemMenuSaveMove: `${BASE_URL}/system/menu/move`,
    SystemMenuDelete: `${BASE_URL}/system/menu/delete`,
    SystemMenuFindById: `${BASE_URL}/system/menu`,
    SystemMenuPermission: `${BASE_URL}/system/menu/permission`,
    SystemMenuIsShowMenu: `${BASE_URL}/system/menu/isshowmenu`,
    SystemMenuHaveMenuPermission: `${BASE_URL}/system/menu/havemenupermission`,
    SystemMenuHaveDataPermission: `${BASE_URL}/system/menu/havedatapermission`,
    SystemMenuHaveFieldPermission: `${BASE_URL}/system/menu/havefieldpermission`,
    SystemMenuHaveButtonPermission: `${BASE_URL}/system/menu/havebuttonpermission`,
    SystemMenuIsFreeze: `${BASE_URL}/system/menu/isfreeze`,

    SystemMenuButtonQuery: `${BASE_URL}/system/menubutton/list`,
    SystemMenuButtonSave: `${BASE_URL}/system/menubutton`,
    SystemMenuButtonSaveAll: `${BASE_URL}/system/menubutton/all`,
    SystemMenuButtonDelete: `${BASE_URL}/system/menubutton/delete`,
    SystemMenuButtonFindById: `${BASE_URL}/system/menubutton`,
    SystemMenuButtonIsFreeze: `${BASE_URL}/system/menubutton/isfreeze`,
    SystemMenuButtonIsShowTable: `${BASE_URL}/system/menubutton/isShowTable`,

    SystemDataQuery: `${BASE_URL}/system/data/list`,
    SystemDataSave: `${BASE_URL}/system/data`,
    SystemDataDelete: `${BASE_URL}/system/data/delete`,
    SystemDataFindById: `${BASE_URL}/system/data`,
    SystemDataIsFreeze: `${BASE_URL}/system/data/isfreeze`,

    SystemDictionary: `${BASE_URL}/system/dictionary`,
    SystemDictionaryQuery: `${BASE_URL}/system/dictionary/list`,
    SystemDictionarySave: `${BASE_URL}/system/dictionary`,
    SystemDictionaryDelete: `${BASE_URL}/system/dictionary/delete`,
    SystemDictionaryFindById: `${BASE_URL}/system/dictionary`,
    SystemDictionaryFindByParentId: `${BASE_URL}/system/dictionary/parentid`,
    SystemDictionaryFindByParentIds: `${BASE_URL}/system/dictionary/parentids`,
    SystemDictionaryIsFreeze: `${BASE_URL}/system/dictionary/isfreeze`,

    SystemDistrict: `${BASE_URL}/system/district/sync`,
    SystemDistrictQuery: `${BASE_URL}/system/district/list`,

    SystemExceptionLogQuery: `${BASE_URL}/system/log/exception`,
    SystemExceptionLogById: `${BASE_URL}/system/log/exception`,
    SystemOperationLogQuery: `${BASE_URL}/system/log/operation`,
    SystemOperationLogById: `${BASE_URL}/system/log/operation`,
    SystemLoginLogQuery: `${BASE_URL}/system/log/login`,
    SystemLoginLogAnalysis: `${BASE_URL}/system/log/login/analysis`,
    SystemRateLimitLogQuery: `${BASE_URL}/system/log/ratelimit`,
    SystemRateLimitLogById: `${BASE_URL}/system/log/ratelimit`,
    SystemSmsLogQuery: `${BASE_URL}/system/log/sms`,
    SystemSmsLogById: `${BASE_URL}/system/log/sms`,

    SystemTxtLogQuery: `${BASE_URL}/system/log/txt`,
    SystemTxtLogDetail: `${BASE_URL}/system/log/txt/path`,

    SystemOrganization: `${BASE_URL}/system/organization`,
    SystemOrganizationRemoveChildren: `${BASE_URL}/system/organization/removechildren`,
    SystemOrganizationQuery: `${BASE_URL}/system/organization/list`,
    SystemOrganizationSave: `${BASE_URL}/system/organization`,
    SystemOrganizationDelete: `${BASE_URL}/system/organization/delete`,
    SystemOrganizationFindById: `${BASE_URL}/system/organization`,
    SystemOrganizationIsFreeze: `${BASE_URL}/system/organization/isfreeze`,
    SystemOrganizationTreeRange: `${BASE_URL}/system/organization/range`,
    SystemOrganizationTopOrg: `${BASE_URL}/system/organization/toporg`,
    SystemOrganizationDownImportTemplate: `${BASE_URL}/system/organization/import/template`,
    SystemOrganizationImport: `${BASE_URL}/system/organization/import`,

    SystemUserOrganization: `${BASE_URL}/system/user/organization`,
    SystemUserQuery: `${BASE_URL}/system/user/list`,
    SystemUserSave: `${BASE_URL}/system/user`,
    SystemUserDelete: `${BASE_URL}/system/user/delete`,
    SystemUserFindById: `${BASE_URL}/system/user`,
    SystemUserDetail: `${BASE_URL}/system/user/detail`,
    SystemUserCheckCode: `${BASE_URL}/system/user/checkcode`,
    SystemUserResetPassword: `${BASE_URL}/system/user/resetpassword`,
    SystemUserChangePassword: `${BASE_URL}/system/user/changepassword`,
    SystemUserCheckPasswordRule: `${BASE_URL}/system/user/checkpasswordrule`,
    SystemUserIsFreeze: `${BASE_URL}/system/user/isfreeze`,
    SystemUserTopOrg: `${BASE_URL}/system/user/toporg`,
    SystemUserDownImportTemplate: `${BASE_URL}/system/user/import/template`,
    SystemUserImport: `${BASE_URL}/system/user/import`,
    SystemUserImportMobile: `${BASE_URL}/system/user/import/mobile`,
    SystemUserHeadImage: `${BASE_URL}/system/user/headimage`,
    SystemUserExport: `${BASE_URL}/system/user/export`,

    SystemRoleOrganization: `${BASE_URL}/system/role/organization`,
    SystemRoleQuery: `${BASE_URL}/system/role/list`,
    SystemRoleSave: `${BASE_URL}/system/role`,
    SystemRoleDelete: `${BASE_URL}/system/role/delete`,
    SystemRoleFindById: `${BASE_URL}/system/role`,
    SystemRoleSelect: `${BASE_URL}/system/role/select`,
    SystemRoleCopy: `${BASE_URL}/system/role/copy`,
    SystemRoleIsFreeze: `${BASE_URL}/system/role/isfreeze`,
    SystemRoleAll: `${BASE_URL}/system/role/all`,

    SystemGroupOrganization: `${BASE_URL}/system/group/organization`,
    SystemGroupQuery: `${BASE_URL}/system/group/list`,
    SystemGroupSave: `${BASE_URL}/system/group`,
    SystemGroupDelete: `${BASE_URL}/system/group/delete`,
    SystemGroupFindById: `${BASE_URL}/system/group`,
    SystemGroupIsFreeze: `${BASE_URL}/system/group/isfreeze`,
    SystemGroupAll: `${BASE_URL}/system/group/all`,

    SystemPostOrganization: `${BASE_URL}/system/post/organization`,
    SystemPostQuery: `${BASE_URL}/system/post/list`,
    SystemPostSave: `${BASE_URL}/system/post`,
    SystemPostDelete: `${BASE_URL}/system/post/delete`,
    SystemPostFindById: `${BASE_URL}/system/post`,
    SystemPostIsFreeze: `${BASE_URL}/system/post/isfreeze`,
    SystemPostAll: `${BASE_URL}/system/post/all`,

    SystemCommonChosenUser: `${BASE_URL}/system/common/chosenuser`,
    SystemCommonChosenUserSave: `${BASE_URL}/system/common/chosenuser`,
    SystemCommonMenuButton: `${BASE_URL}/system/permission/menubutton`,

    SystemPermissionMenu: `${BASE_URL}/system/permission/menu`,
    SystemPermissionPrivilegeMaster: `${BASE_URL}/system/permission/privilegemaster`,
    SystemPermissionSave: `${BASE_URL}/system/permission`,
    SystemPermissionMenuHave: `${BASE_URL}/system/permission/menuhave`,
    SystemPermissionMenuButton: `${BASE_URL}/system/permission/menubutton`,
    SystemPermissionMenuButtonAll: `${BASE_URL}/system/permission/menubuttonall`,
    SystemPermissionDetail: `${BASE_URL}/system/permission/detail`,
    SystemPermissionData: `${BASE_URL}/system/permission/data`,
    SystemPermissionDataAll: `${BASE_URL}/system/permission/dataall`,

    SystemNoticeQuery: `${BASE_URL}/system/notice/list`,
    SystemNoticeSave: `${BASE_URL}/system/notice`,
    SystemNoticeDelete: `${BASE_URL}/system/notice/delete`,
    SystemNoticeFindById: `${BASE_URL}/system/notice`,

    SystemDataSourceQuery: `${BASE_URL}/system/datasource/list`,
    SystemDataSourceSave: `${BASE_URL}/system/datasource`,
    SystemDataSourceDelete: `${BASE_URL}/system/datasource/delete`,
    SystemDataSourceFindById: `${BASE_URL}/system/datasource`,

    SystemDataBaseQuery: `${BASE_URL}/system/database/list`,
    SystemDataBaseSave: `${BASE_URL}/system/database`,
    SystemDataBaseDelete: `${BASE_URL}/system/database/delete`,
    SystemDataBaseFindById: `${BASE_URL}/system/database`,

    SystemJobQuery: `${BASE_URL}/system/job/list`,
    SystemJobLogQuery: `${BASE_URL}/system/log/job`,
    SystemJobSchedule: `${BASE_URL}/system/job/schedule`,
    SystemJobDelete: `${BASE_URL}/system/job/delete`,
    SystemJobEdit: `${BASE_URL}/system/job/edit`,
    SystemJobPause: `${BASE_URL}/system/job/pause`,
    SystemJobPauseAll: `${BASE_URL}/system/job/pauseall`,
    SystemJobResume: `${BASE_URL}/system/job/resume`,
    SystemJobResumeAll: `${BASE_URL}/system/job/resumeall`,

    SystemJobCalendarQuery: `${BASE_URL}/system/job/calendar`,
    SystemJobCalendarEdit: `${BASE_URL}/system/job/calendar/edit`,
    SystemJobCalendarDelete: `${BASE_URL}/system/job/calendar/delete`,
    SystemJobCalendarSave: `${BASE_URL}/system/job/calendar/save`,

    SystemFileUpload: `${BASE_URL}/system/file/uploadform`,
    SystemFileCorrelationId: `${BASE_URL}/system/file/correlation`,
    SystemFileUploadDel: `${BASE_URL}/system/file/delete`,
    SystemFileUploadReurnPaths: `${BASE_URL}/system/file/uploadreturnpath`,

    SystemUpdateLogQuery: `${BASE_URL}/system/updatelog/list`,

    SystemMaterialQuery: `${BASE_URL}/system/material/list`,
    SystemMaterialSave: `${BASE_URL}/system/material`,
    SystemMaterialDelete: `${BASE_URL}/system/material/delete`,
    SystemMaterialFindById: `${BASE_URL}/system/material`,

    SystemMessageLogQuery: `${BASE_URL}/system/messagelog/list`,
    SystemMessageLogFindById: `${BASE_URL}/system/messagelog`,
    SystemMessageLogRead: `${BASE_URL}/system/messagelogread`,
    SystemMessageLogMy: `${BASE_URL}/system/messagelog/list/my`,

    SystemSnQuery: `${BASE_URL}/system/sn`,

    SystemLeaderQuery: `${BASE_URL}/system/userleader`,
    SystemLeaderSave: `${BASE_URL}/system/userleader`,
    SystemLeaderSubordinateQuery: `${BASE_URL}/system/userleader/subordinate`,
    SystemLeaderSubordinateSave: `${BASE_URL}/system/userleader/subordinate`,

    SystemSmsTemplateQuery: `${BASE_URL}/system/smstemplate/list`,
    SystemSmsTemplateSave: `${BASE_URL}/system/smstemplate`,
    SystemSmsTemplateDelete: `${BASE_URL}/system/smstemplate/delete`,
    SystemSmsTemplateFindById: `${BASE_URL}/system/smstemplate`,

    SystemSearchQuery: `${BASE_URL}/system/search/list`,
    SystemSearchSave: `${BASE_URL}/system/search`,
    SystemSearchDelete: `${BASE_URL}/system/search/delete`,
    SystemSearchFindById: `${BASE_URL}/system/search`,

    SystemSmsConfigQuery: `${BASE_URL}/system/smsconfig/list`,
    SystemSmsConfigSave: `${BASE_URL}/system/smsconfig`,
    SystemSmsConfigDelete: `${BASE_URL}/system/smsconfig/delete`,
    SystemSmsConfigFindById: `${BASE_URL}/system/smsconfig`,

    //敏捷开发
    SystemAgileQuery: `${BASE_URL}/system/agile/config/list`,
    SystemAgileSave: `${BASE_URL}/system/agile/config`,
    SystemAgileSaveType: `${BASE_URL}/system/agile/config/type`,
    SystemAgileSaveThumbnail: `${BASE_URL}/system/agile/config/save/thumbnail`,
    SystemAgileSaveJson: `${BASE_URL}/system/agile/config/save/json`,
    SystemAgilePublicJson: `${BASE_URL}/system/agile/config/public/json`,
    SystemAgileDelete: `${BASE_URL}/system/agile/config/delete`,
    SystemAgileFindById: `${BASE_URL}/system/agile/config`,
    SystemAgileFindByMenuId: `${BASE_URL}/system/agile/config/menu`,
    SystemAgileBase: `${BASE_URL}/system/agile/config/base`,
    SystemAgileColumns: `${BASE_URL}/system/agile/config/columns`,
    SystemAgileIsFreeze: `${BASE_URL}/system/agile/config/isfreeze`,
    SystemAgileFindColumnJsonByDataFromName: `${BASE_URL}/system/agile/config/columnjson/datafromname`,
    SystemAgileFindColumnJsonByMenuId: `${BASE_URL}/system/agile/config/columnjson/menuid`,
    SystemAgileDataLogRelationId: `${BASE_URL}/system/agile/datalog/relationid`,
    SystemAgileQueryKey: `${BASE_URL}/system/agile/config/key`,

    SystemAgileAutomationQuery: `${BASE_URL}/system/agileautomation/list`,
    SystemAgileAutomationSave: `${BASE_URL}/system/agileautomation`,
    SystemAgileAutomationDelete: `${BASE_URL}/system/agileautomation/delete`,
    SystemAgileAutomationFindById: `${BASE_URL}/system/agileautomation`,
    SystemAgileAutomationIsFreeze: `${BASE_URL}/system/agileautomation/isfreeze`,
    SystemAgileAutomationSaveJson: `${BASE_URL}/system/agileautomation/save/json`,
    SystemAgileAutomationPublicJson: `${BASE_URL}/system/agileautomation/public/json`,
    SystemAgileAutomationTable: `${BASE_URL}/system/agileautomation/table`,
    SystemAgileAutomationRun: `${BASE_URL}/system/agileautomation/run`,

    SystemDataBaseIsTableExist: `${BASE_URL}/system/database/tableexist`,
    SystemDataBaseSaveFormTable: `${BASE_URL}/system/database/table/save`,
    SystemDataBaseSaveFormTableField: `${BASE_URL}/system/database/tablefield`,
    SystemDataBaseTable: `${BASE_URL}/system/database/table`,
    SystemDataBaseTableColumn: `${BASE_URL}/system/database/column`,
    SystemDataBaseTableSpaceused: `${BASE_URL}/system/database/spaceused`,
    SystemDataBaseProc: `${BASE_URL}/system/database/proc`,
    SystemDataBaseView: `${BASE_URL}/system/database/view`,
    SystemDataBaseTableTree: `${BASE_URL}/system/database/table/tree`,
    SystemDataBaseBusinessData: `${BASE_URL}/system/database/businessdata`,
    SystemDataBaseBusinessDataFooter: `${BASE_URL}/system/database/businessdata/footer`,
    SystemDataBaseBusinessDataQuery: `${BASE_URL}/system/database/businessdata/list`, //查询数据
    SystemDataBaseBusinessDataQueryFilterSearch: `${BASE_URL}/system/database/businessdata/list/filtersearch`,
    SystemDataBaseBusinessDataQueryPage: `${BASE_URL}/system/database/businessdata/page`, //查询数据
    SystemDataBaseBusinessDataFindById: `${BASE_URL}/system/database/businessdata/byid`,

    SystemDataBaseBusinessDataDel: `${BASE_URL}/system/database/businessdata/del`,
    SystemDataBaseBusinessDataDelPhysics: `${BASE_URL}/system/database/businessdata/del/physics`,
    SystemDataBaseBusinessDataDelPhysicsAll: `${BASE_URL}/system/database/businessdata/del/physics/all`,
    SystemDataBaseBusinessDataDelRecovery: `${BASE_URL}/system/database/businessdata/del/recovery`,

    SystemDataBaseBusinessDataQueryBatch: `${BASE_URL}/system/database/businessdata/batch/list`,
    SystemDataBaseBusinessDataFindFormSource: `${BASE_URL}/system/database/businessdata/fromsource`,
    SystemDataBaseBusinessDataFindFormSourcePaging: `${BASE_URL}/system/database/businessdata/fromsourcepaging`,
    SystemDataBaseBusinessDataFindFormSourcePagingTable: `${BASE_URL}/system/database/businessdata/fromsourcepaging/table`,
    SystemDataBaseBusinessDataReport: `${BASE_URL}/system/database/businessdata/report`,
    SystemDataBaseBusinessDataReportTemplate: `${BASE_URL}/system/database/businessdata/report/template`,
    SystemDataBaseBusinessDataImport: `${BASE_URL}/system/database/businessdata/import`,
    SystemDataBaseBusinessDataImportTable: `${BASE_URL}/system/database/businessdata/import/table`,
    SystemDataBaseBusinessDataImportGet: `${BASE_URL}/system/database/businessdata/import/data`,
    SystemDataBaseBusinessDataImportTemplate: `${BASE_URL}/system/database/businessdata/import/template`,

    SystemEventApi: `${BASE_URL}/system/agile/event/api`,
    SystemCodeGenerationCode: `${BASE_URL}/system/codegeneration/code`,
    SystemCodeGenerationFile: `${BASE_URL}/system/codegeneration/file`,

    //工作流
    WorkflowButtonQuery: `${BASE_URL}/workflow/button/list`,
    WorkflowButtonSave: `${BASE_URL}/workflow/button`,
    WorkflowButtonDelete: `${BASE_URL}/workflow/button/delete`,
    WorkflowButtonFindById: `${BASE_URL}/workflow/button`,

    WorkflowProcessQuery: `${BASE_URL}/workflow/process/list`,
    WorkflowProcessSave: `${BASE_URL}/workflow/process`,
    WorkflowProcessSaveDesignJson: `${BASE_URL}/workflow/process/json`,
    WorkflowProcessDelete: `${BASE_URL}/workflow/process/delete`,
    WorkflowProcessFindById: `${BASE_URL}/workflow/process`,
    WorkflowProcessSaveThumbnail: `${BASE_URL}/workflow/process/thumbnail`,

    WorkflowPermission: `${BASE_URL}/workflow/permission`,
    WorkflowPermissionFind: `${BASE_URL}/workflow/permission/find`,
    WorkflowPermissionSave: `${BASE_URL}/workflow/permission`,

    WorkflowCommentQuery: `${BASE_URL}/workflow/comment/list`,
    WorkflowCommentSave: `${BASE_URL}/workflow/comment`,
    WorkflowCommentDelete: `${BASE_URL}/workflow/comment/delete`,
    WorkflowCommentFindById: `${BASE_URL}/workflow/comment`,
    WorkflowCommentMy: `${BASE_URL}/workflow/comment/my`,

    WorkflowEngineColumn: `${BASE_URL}/workflow/engine/column`,
    WorkflowEngineLibrary: `${BASE_URL}/workflow/engine/library`,
    WorkflowEngineActivityStart: `${BASE_URL}/workflow/engine/activity/start`,
    WorkflowEngineStart: `${BASE_URL}/workflow/engine/start`,
    WorkflowEngineStartRun: `${BASE_URL}/workflow/engine/start/run`,
    WorkflowEngineTaskProcess: `${BASE_URL}/workflow/engine/taskprocess`,
    WorkflowEngineTaskProcessRun: `${BASE_URL}/workflow/engine/taskprocess/run`,

    WorkflowEngineNeedDo: `${BASE_URL}/workflow/engine/needdo`,
    WorkflowEngineHaveDo: `${BASE_URL}/workflow/engine/havedo`,
    WorkflowEngineHaveSend: `${BASE_URL}/workflow/engine/havesend`,
    WorkflowEngineOverTime: `${BASE_URL}/workflow/engine/overtime`,
    WorkflowEngineInstanceProcess: `${BASE_URL}/workflow/engine/instanceprocess`,
    WorkflowEngineActivityByTaskId: `${BASE_URL}/workflow/activity/task`,
    WorkflowEngineTaskById: `${BASE_URL}/workflow/engine/task`,
    WorkflowEngineEvent: `${BASE_URL}/workflow/engine/event`,

    WorkflowEngineRefuse: `${BASE_URL}/workflow/engine/refuse`,
    WorkflowEngineReturnAndWrite: `${BASE_URL}/workflow/engine/returnandwrite`,
    WorkflowEngineReturnActivity: `${BASE_URL}/workflow/engine/returnactivity`,
    WorkflowEngineUnderStanding: `${BASE_URL}/workflow/engine/understanding`,
    WorkflowEngineUnderStandingRead: `${BASE_URL}/workflow/engine/understanding/read`,

    WorkflowEngineInvitationRead: `${BASE_URL}/workflow/engine/invitationread`,
    WorkflowEngineInvitationReadSure: `${BASE_URL}/workflow/engine/invitationread/sure`,
    WorkflowEngineInvitationReadApprove: `${BASE_URL}/workflow/engine/invitationread/approve`,
    WorkflowEngineInvitationReadApprovePass: `${BASE_URL}/workflow/engine/invitationread/approve/pass`,
    WorkflowEngineInvitationReadApproveRefuse: `${BASE_URL}/workflow/engine/invitationread/approve/refuse`,
    WorkflowEngineRevoke: `${BASE_URL}/workflow/engine/revoke`,
    WorkflowEngineEnd: `${BASE_URL}/workflow/engine/end`,
    WorkflowEngineAdd: `${BASE_URL}/workflow/engine/add`,
    WorkflowEngineAddApprove: `${BASE_URL}/workflow/engine/add/approve`,
    WorkflowEngineDeleteTask: `${BASE_URL}/workflow/engine/delete/task`,
    WorkflowEngineRevokeByCreateUser: `${BASE_URL}/workflow/engine/revoke/createuser`,

    WorkflowEngineMonitorQuery: `${BASE_URL}/workflow/engine/monitor`,
    WorkflowEngineMonitorDetail: `${BASE_URL}/workflow/engine/detail`,
    WorkflowEngineMonitorArchive: `${BASE_URL}/workflow/engine/archive`,

    WorkflowEngineDraftSave: `${BASE_URL}/workflow/engine/draft`,
    WorkflowEngineDraftQuery: `${BASE_URL}/workflow/engine/draft/query`,
    WorkflowEngineDraftDelete: `${BASE_URL}/workflow/engine/draft/del`,

    WorkflowEngineModelSave: `${BASE_URL}/workflow/engine/model`,
    WorkflowEngineModelQuery: `${BASE_URL}/workflow/engine/model/query`,
    WorkflowEngineModelDelete: `${BASE_URL}/workflow/engine/model/del`,
    WorkflowEngineFlowChart: `${BASE_URL}/workflow/engine/flowchart`,

    //微信相关
    WeChatUserQuery: `${BASE_URL}/wechat/user/list`,
    WeChatUserBindUserQuery: `${BASE_URL}/wechat/user/bind/finduser`,
    WeChatUserBindOrganizationQuery: `${BASE_URL}/wechat/user/bind/findorganization`,
    WeChatUserBindSave: `${BASE_URL}/wechat/user/bind`,
    WeChatUserUnBind: `${BASE_URL}/wechat/user/unbind`,

    WeChatMpTemplateQuery: `${BASE_URL}/wechat/mp/template/list`,
    WeChatMpTemplateSave: `${BASE_URL}/wechat/mp/template`,
    WeChatMpTemplateDelete: `${BASE_URL}/wechat/mp/template/delete`,
    WeChatMpTemplateFindById: `${BASE_URL}/wechat/mp/template`,

    WeChatAccountQuery: `${BASE_URL}/wechat/account/list`,
    WeChatAccountSave: `${BASE_URL}/wechat/account`,
    WeChatAccountDelete: `${BASE_URL}/wechat/account/delete`,
    WeChatAccountFindById: `${BASE_URL}/wechat/account`,

    WeChatMpTemplateSendQuery: `${BASE_URL}/wechat/mp/template/send/list`,
    WeChatMpTemplateSendSave: `${BASE_URL}/wechat/mp/template/send`,
    WeChatMpTemplateSendDelete: `${BASE_URL}/wechat/mp/template/send/delete`,
    WeChatMpTemplateSendFindById: `${BASE_URL}/wechat/mp/template/send`,
    WeChatMpTemplateSendSaveStart: `${BASE_URL}/wechat/mp/template/send/save`,
    WeChatMpTemplateSendPreview: `${BASE_URL}/wechat/mp/template/send/preview`,

    WeChatWorkDepartmentTree: `${BASE_URL}/wechat/work/department/tree`,
    WeChatWorkDepartmentQuery: `${BASE_URL}/wechat/work/department/list`,
    WeChatWorkDepartmentAsync: `${BASE_URL}/wechat/work/department/async`,
    WeChatWorkDepartmentAsyncToSystem: `${BASE_URL}/wechat/work/department/async/system`,

    WeChatWorkUserAsync: `${BASE_URL}/wechat/work/user/async`,
    WeChatWorkUserAsyncToSystem: `${BASE_URL}/wechat/work/user/async/system`,
    WeChatWorkUserQuery: `${BASE_URL}/wechat/work/user/list`,
    WeChatWorkUserBindUserId: `${BASE_URL}/wechat/work/user/bind/userid`,

    DingTalkDepartmentTree: `${BASE_URL}/dingtalk/department/tree`,
    DingTalkDepartmentQuery: `${BASE_URL}/dingtalk/department/list`,
    DingTalkDepartmentAsync: `${BASE_URL}/dingtalk/department/async`,
    DingTalkDepartmentAsyncToSystem: `${BASE_URL}/dingtalk/department/async/system`,

    DingTalkUserAsync: `${BASE_URL}/dingtalk/user/async`,
    DingTalkUserAsyncToSystem: `${BASE_URL}/dingtalk/user/async/system`,
    DingTalkUserQuery: `${BASE_URL}/dingtalk/user/list`,
    DingTalkUserBind: `${BASE_URL}/dingtalk/user/bind`,
    DingTalkUserBindUserId: `${BASE_URL}/dingtalk/user/bind/userid`,
    DingTalkUserTransfer: `${BASE_URL}/dingtalk/user/transfer/system`,
    DingTalkLoginCode: `${BASE_URL}/authorize/account/login/dingtalk`,
}